spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Wjz920206_
    url: jdbc:mysql://47.100.197.234/weichat?characterEncoding=utf-8&useSSL=false
env: dev5
